application: gkhereyouare
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: gkhereyouare.app
  login: admin
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /poll
  script: gkhereyouare.app
  login: admin
- url: /token
  script: gkhereyouare.app
  login: admin

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: yaml
  version: latest

env_variables:
  EPICENTRE_ID: 239927392813748
  FACEBOOK_APP_ID: 358523110942296
  FACEBOOK_APP_SECRET_FILE: gkhereyouare.secret
  RADIUS: 1000
  SCOPE: "friends_photos,friends_status,user_photos,user_status"