application: gkhereyouare
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /
  script: gkhereyouare.app
- url: /poll
  script: gkhereyouare.app
  login: admin
- url: /token
  script: gkhereyouare.app
  login: admin

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: yaml
  version: latest

env_variables:
  APP_ID: 358523110942296
  EPICENTRE_ID: 239927392813748
  RADIUS: 1500