application: gkhereyouare
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: gkhereyouare.app
- url: /poll
  script: gkhereyouare.app
  login: admin
- url: /token
  script: gkhereyouare.app
  login: admin

env_variables:
  APP_ID: 358523110942296
  EPICENTRE_ID: 239927392813748
  RADIUS: 1500